title: "[功能请求]: "
body:
- type: textarea
  attributes:
    label: 问题描述 Problem Statement
    description: 你遇到了什么问题，是目前我们的系统无法提供的？
    placeholder: "示例：多个前端项目（网络和应用程序）需要请求一项新服务，该服务将允许用户注册不同类型的现场活动，例如 BarCitizen, Impacts 等。"
  validations:
    required: true
- type: textarea
  attributes:
    label: 基本认知 Basic Understanding
    description: 为了解决这个问题，我们现有的架构将会怎么做？
    placeholder: "每个现场活动地点都需要自己的服务器、数据库和网站。在没有任何服务器的情况下，当场构建这个系统将非常困难。任何第三方应用程序/电影票应用程序都应与活动的服务器一起获取座位可用性信息。"
  validations:
    required: true
- type: textarea
  attributes:
    label: 功能要求 Functional Requirements
    description: 为了解决这个问题，我们应该新增哪些功能？
    placeholder: "- 用户可以搜索/查看活动\n - 用户可以从活动中注册/取消注册\n - 管理员可以创建/查看/更新/删除活动\n - 管理员可以获取活动的注册用户列表\n - 支持多个城市和国家、线上"
  validations:
    required: true
- type: textarea
  attributes:
    label: 用户与管理员角色 User and Admin Roles
    description: 用户和管理员具有不同的角色，我们是否需要区分？
    placeholder: "- 管理员可以创建/查看/更新/搜索/删除活动。\n - 管理员还可以获取活动的注册用户列表。\n - 户可以注册/注销活动、搜索活动、查看活动。"
  validations:
    required: true
- type: textarea
  attributes:
    label: 用户使用流程 User Usage Flow
    description: 用户在通常情况下会如何使用我们的服务？
  validations:
    required: true
